Repository pyNEMO/pyDOMCFG, pull requests merged in 2021-06, with the labels that each got.

#8 Add code to generate coordinates datasets
  .pre-commit-config.yaml
  ci/docs.yml
  docs/conf.py
  docs/developers/contributing.rst
  docs/developers/whats-new.rst
  docs/users/api.rst
  pydomcfg/__init__.py
  pydomcfg/tests/bathymetry.py
  pydomcfg/tests/test_import.py
  pydomcfg/tests/test_placeholder.py
  pydomcfg/tests/test_utils.py
  pydomcfg/utils.py
  setup.cfg
Labels: enhancement

#12 add git docs
  .pre-commit-config.yaml
  docs/Makefile
  docs/developers/contributing.rst
  docs/developers/whats-new.rst
Labels: documentation

#14 Update environments and installation
  ci/environment.yml
  ci/upstream-dev-env.yml
  docs/index.rst
  docs/users/installing.rst
  setup.cfg
Labels: documentation

#13 Add chunks argument to generate_cartesian_grid
  docs/conf.py
  pydomcfg/utils.py
Labels: enhancement

#28 add 2x2 test
  pydomcfg/tests/test_placeholder.py
  pydomcfg/tests/test_zco.py
Labels: tests

#17 Test configs
  docs/developers/whats-new.rst
  pydomcfg/tests/bathymetry.py
Labels: enhancement, task

#31 Zco: More xarray, tests, and improve/expose docstring
  .pre-commit-config.yaml
  docs/conf.py
  docs/developers/whats-new.rst
  docs/users/api.rst
  pydomcfg/domzgr/zco.py
  pydomcfg/domzgr/zgr.py
  pydomcfg/tests/bathymetry.py
  pydomcfg/tests/data.py
  pydomcfg/tests/test_zco.py
  pydomcfg/utils.py
  setup.cfg
Labels: documentation, enhancement, tests

#36 Implement accessor
  ci/docs.yml
  docs/conf.py
  docs/developers/whats-new.rst
  docs/users/api.rst
  pydomcfg/__init__.py
  pydomcfg/accessor.py
  pydomcfg/domzgr/zco.py
  pydomcfg/tests/test_accessor.py
  pydomcfg/tests/test_zco.py
Labels: enhancement

#40 Do not drop indexes when computing rmax
  pydomcfg/domzgr/zgr.py
  pydomcfg/tests/bathymetry.py
Labels: enhancement

#51 Refactor MB06
  pydomcfg/utils.py
Labels: enhancement
